packages:
  - apps/*
  - packages/*
catalog:
  '@sveltejs/kit': ^2.5.24
  '@typescript-eslint/parser': ^8.27.0
  prettier: ^3.5.3
  svelte: ^4.0.0
  typescript: ^5.8.2
onlyBuiltDependencies:
  - '@sveltejs/kit'
  - svelte-preprocess
