name: Publish
on:
    release:
        types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v7
            - uses: oven-sh/setup-bun@v2.2.0
              with:
                  bun-version: '1.4.0'
            - run: bun install --frozen-lockfile
            - run: bun run build
            - run: bun publish
              working-directory: packages/process
              env:
                  NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
