name: Tests
on:
    pull_request:
        branches: ['**']
permissions:
    contents: read
jobs:
    tests:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node-version: [22.x, 24.x, 26.x]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v7
              with:
                  node-version: ${{ matrix.node-version }}
            - uses: oven-sh/setup-bun@v2.2.0
              with:
                  bun-version: '1.4.0'
            - run: bun install --frozen-lockfile
            - run: bun run build
            - run: bun run test
